### ISSUE TITLE
why are you using singleton patterns?

### ISSUE THREAD

**Issue by moebiussurfing** [tettou771/ofxTextFlow#1]
thanks for sharing.
not an issue, but I am just curious to learning purposes:
I see that besides other "normal classes" you don't need to call .draw() on ofApp,
I ask about it because I read sometimes that is "not recommended" to use singleton and I want to know what are the good points or pros in this case.
It's maybe some "global" access from anywhere on all the app scope?

**Comment by moebiussurfing** [comment]
@tettou771 , i see that your are using mutex too, so maybe there's also some multi thread benefits?

**Comment by tettou771** [comment]
I'm glad you interested to my code!

Yes, I used mutex to compatible with multithread code.

It is makes sense that we not use singleton or global value. But, I wanna use ofxTextFlow for debug comment. It is like ofLog().
